GET http://localhost:3500/api/products
x-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW50aG9ueSBGaW5peCIsInVzZXJuYW1lIjoiYW50aG9ueWZpbml4IiwiZW1haWwiOiJhbnRob255ZmluaXhAZ21haWwuY29tIiwiaWF0IjoxNjAzNzA2NDkwLCJleHAiOjE2MDM3MDcwOTB9.qOT5prM0_EujDhWEO1PRxiBNDoOBooi-3xlWc0XIdH4
###
GET http://localhost:3500/api/clients
x-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW50aG9ueSBGaW5peCIsInVzZXJuYW1lIjoiYW50aG9ueWZpbml4IiwiZW1haWwiOiJhbnRob255ZmluaXhAZ21haWwuY29tIiwiaWF0IjoxNjAzNzA2NDkwLCJleHAiOjE2MDM3MDcwOTB9.qOT5prM0_EujDhWEO1PRxiBNDoOBooi-3xlWc0XIdH4
###
GET http://localhost:3500/api/invoices
x-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW50aG9ueSBGaW5peCIsInVzZXJuYW1lIjoiYW50aG9ueWZpbml4IiwiZW1haWwiOiJhbnRob255ZmluaXhAZ21haWwuY29tIiwiaWF0IjoxNjAzNzA2NDkwLCJleHAiOjE2MDM3MDcwOTB9.qOT5prM0_EujDhWEO1PRxiBNDoOBooi-3xlWc0XIdH4